### ISSUE TITLE
`peaksData<-` not implemented for MsBackendCompDB and MsBackendMassbankSql

### ISSUE THREAD

**Issue by zmahnoor14** [jorainer/SpectraTutorials#29]
Dear amazing Spectra Team,

I have been using Spectra since 2021 April and its a great package.

I have a request here, in order to pre-process some spectra from HMDB and MassBank and then to overwrite the pre-processed spectra, I would like to access spectra object via "peaksData<-" assignment. It is possible with MsBackendMsp, MsBackendMgf, and MsBackendMzR. Is it possible to implement this functionality in MsBackendCompDB and MsBackendMassbankSql as well?

Kind regards,
Mahnoor

**Comment by jorainer** [comment]
Hi Mahnoor,

thanks for the suggestion, but I would definitely not like to have a `peaksData<-` for the `MsBackendMassbankSql` because the whole idea for that backend was to provide read-only access to the MassBank database. For `MsBackendCompDb` we could think of adding that, but also here, the idea was to have access to a read-only backend.

Currently, for both backends it would still be possible to perform the data manipulations on the `Spectra` object - they then don't get stored into the database but *only* cached in the `Spectra` object. Is that not something you could use instead? Or could you maybe please describe your use? Then it's sometimes easier to find the solution for the specific problem.

**Comment by jorainer** [comment]
OK, I think I got it now. A *quick* solution would be to change the backend for all data bases to the `MsBackendDataFrame` which supports, like you did, the `peaksData(sps@backend) <- pkd` call.

To change the backend you could use:

```r
sps <- setBackend(sps, backend = MsBackendDataFrame())
```

**Comment by zmahnoor14** [comment]
Thanks for the answer. I tried it and got this error message for hmdb stored in ```MsBackendCompDb```. Here I am not using the whole HMDB but the subsection that has precursor mass 273.1846999 just for faster calculations.
```r
sps_hmdb <- setBackend(sps_hmdb, backend = MsBackendDataFrame())
```

```Error: BiocParallel errors
  1 remote errors, element index: 1
  0 unevaluated and other errors
  first remote error:
Error in validObject(object): invalid object of the class “MsBackendDataFrame”: The following columns have a wrong data type: collisionEnergy. The expected data type(s) is/are: numeric.

Traceback:

1. setBackend(sps_hmdb, backend = MsBackendDataFrame())
2. setBackend(sps_hmdb, backend = MsBackendDataFrame())
3. .local(object, backend, ...)
4. bplapply(split(object@backend, f = f), function(z, ...) {
 .     backendInitialize(backend, data = spectraData(z), ..., BPPARAM = SerialParam())
 . }, ..., BPPARAM = BPPARAM)
5. bplapply(split(object@backend, f = f), function(z, ...) {
 .     backendInitialize(backend, data = spectraData(z), ..., BPPARAM = SerialParam())
 . }, ..., BPPARAM = BPPARAM)
6. .bpinit(manager = manager, X = X, FUN = FUN, ARGS = ARGS, BPPARAM = BPPARAM, 
 .     BPOPTIONS = BPOPTIONS, BPREDO = BPREDO)
```

And the entries in HMDB for collision energy are:
```r
sps_hmdb$collisionEnergy
```

```
#example
NA . '30' .......... '20'
```

**Comment by jorainer** [comment]
Ah, yes. That's a bug (that I fixed in the current devel version). Before changing the backend I suggest to replace the `collisionEnergy` values by converting them to numeric: `sps_hmdb$collisionEnergy <- as.numeric(sps_hmdb$collisionEnergy)`. After that the `setBackend` call should work.

**Comment by zmahnoor14** [comment]
Dear Johannes,

thanks a lot : D It works now : )

Kind regards,
Mahnoor
